# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af617a91de90660267e878c4812b963713de82ab299c3d741ff56175776f5cbe405d9fe2d1d7886334db64a4fce406cdb36b6c16d0c5f43cd2174ecdcce82944

test:
  secret_key_base: 3d0fe01f89a30604a5b334492bfcb3bfa01528d67b43b71e9882d65fdeab5ae62d3519caa0b99887d831db9f44af0e6d8fe41e804c009c997ebd573c06618d07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
